### PR TITLE
Change to use for Kodi Matrix and version increase

### PR DESCRIPTION
**Pull request by AlwinEsch**
This is for last changes on Kodi to use this for Matrix.

> note: Leia is still default branch

### CODE REVIEW

**Comment by Rechi** [comment]
I don't see a reason why `screensaver.asteroids` has to be recompiled. Looking at the used interface versions of 2.3.0 compiled for Leia, they are still compatible with Matrix (at the time of writing this comment).

**Comment by AlwinEsch** [comment]
It's about https://github.com/xbmc/xbmc/commit/22624c6d0655ffba9c0aec42ab6025e2a6fef8f9#diff-6f17183223c4451cae43f275b9767144
and after the fix with https://github.com/xbmc/xbmc/pull/16458

Related to https://github.com/xbmc/screensaver.asteroids/blob/Leia/src/main.h#L13-L14

**Comment by Rechi** [comment]
Xcode 10.2 is used for Matrix on Jenkins, Travis CI should use the same version of Xcode.

**Comment by AlwinEsch** [comment]
Sorry, has compared it with https://github.com/kodi-pvr/pvr.hts/commit/8b06c178d6748b4bd8639e728d48f700b72b16df#diff-354f30a63fb0907d4ad57269548329e3R35 and there was this not done, becomes changed.

**Comment by AlwinEsch** [comment]
Change finished and test OK.

**Change master to Matrix branch still required**

**Comment by AlwinEsch** [comment]
After recent changes, it is now running smoothly on Linux, on Windows and on Jenkins created Windows addon.

**Pull request merged**
